# Generated by Django 3.0.5 on 2021-05-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ab_testing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='timestamp',
        ),
    ]
